USE OOTP
GO
--This will create a database called OOTP, a schema called
--Player, a table called SecondBasemen, and populate that table.
--The table is a standard table, but we'll use it with some
--Polybase offerings.
IF NOT EXISTS
(
	SELECT 1
	FROM sys.databases d
	WHERE
		d.name = N'OOTP'
)
BEGIN
	CREATE DATABASE OOTP;
END
GO
USE [OOTP]
GO
IF NOT EXISTS
(
	SELECT 1
	FROM sys.schemas s
	WHERE
		s.name = N'Player'
)
BEGIN
	--Schema creation may be the only thing in the batch.
	EXEC(N'CREATE SCHEMA Player');
END
GO
IF (OBJECT_ID('Player.SecondBasemen') IS NULL)
BEGIN
	CREATE TABLE [Player].[SecondBasemen](
		[FirstName] [varchar](50) NULL,
		[LastName] [varchar](50) NULL,
		[Age] [int] NULL,
		[Bats] [varchar](5) NULL,
		[Throws] [varchar](5) NULL
	) ON [PRIMARY];

	INSERT INTO Player.SecondBasemen VALUES('Casey', 'Turgeon', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jared', 'Foster', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Vidal', 'Brujan', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jesus', 'Guerra', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Pimentel', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Austin', 'Slater', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jesus', 'Henriquez', 16, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos A.', 'Guzman', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yander', 'Martinez', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Edgar', 'Rondon', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Howell', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('David', 'Walker', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Grant', 'Cox', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Justin', 'Montemayor', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Aaron', 'Wilson', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jeff', 'Smith', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chris', 'Godinez', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Stefan', 'Trosclair', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chase', 'Nyman', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kurt', 'Hoekstra', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Drew', 'Turbin', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Melvin', 'Rodriguez', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jace', 'Conrad', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brett', 'Sullivan', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Peter', 'Maris', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Erik', 'Forgione', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Trent', 'Gilbert', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jordan', 'Tarsovich', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Peter', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kevin', 'Kramer', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dante', 'Flores', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sutton', 'Whiting', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Deion', 'Ulmer', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jhonny', 'Bethencourt', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Logan', 'Ratledge', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Stephen', 'Pitarra', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Grant', 'Williams', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Greg', 'Deichmann', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Forrest', 'Wall', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luke', 'Dykstra', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Jarvis', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Lane', 'Thomas', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Shane', 'Mardirosian', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Christopher', 'Martin', 15, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Payton', 'Squier', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Taylor', 'Hawthorne', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jesse', 'Russo', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Lincoln', 'Clayton', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Felipe', 'Lopez', 34, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ramon', 'Santiago', 35, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Omar', 'Infante', 33, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chone', 'Figgins', 37, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brandon', 'Phillips', 33, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chase', 'Cryer', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rickie', 'Weeks', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chase', 'Utley', 36, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ruben', 'Gotay', 32, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Donnie', 'Murphy', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brendan', 'Harris', 34, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Slade', 'Dale', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Maicer', 'Izturis', 34, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Josh', 'Wilson', 33, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kelly', 'Johnson', 33, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Skip', 'Schumaker', 35, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Aaron', 'Hill', 33, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mike', 'Fontenot', 34, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Pete', 'Orr', 35, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ronny', 'Cedeno', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robinson', 'Cano', 32, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kevin', 'Frandsen', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ian', 'Kinsler', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dan', 'Uggla', 35, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Stephen', 'Drew', 32, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ben', 'Zobrist', 33, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dustin', 'Pedroia', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Howie', 'Kendrick', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Roberts', 34, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yunel', 'Escobar', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Marshall', 'Smith', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jamie', 'Galazin', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alberto', 'Gonzalez', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Emilio', 'Bonifacio', 29, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Justin', 'Trochiano', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Edgar V.', 'Gonzalez', 36, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jonathan', 'Herrera', 30, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hernan', 'Iribarren', 30, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Edwin', 'Maysonet', 33, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Daniel', 'Murphy', 29, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jayson', 'Nix', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sean', 'Rodriguez', 29, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Adam', 'Rosales', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kent', 'Burckle', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Vinny', 'Esposito', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'McGoldrick', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jaylen', 'Hubbard', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dalton', 'Guthrie', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Haakon', 'Lande', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Daniel', 'Calabretta', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jared', 'Williams', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jaime', 'Estrada', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dan', 'Hennigan', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Daane', 'Berezo', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carson', 'Vanlandingham', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Shepski', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Urwin', 'Juaquin', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robbie', 'Metz', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brian', 'Mims', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dale', 'Burdick', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brady', 'Acton', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Clay', 'Fisher', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alex', 'Dirienzo', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tucker', 'Cascadden', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Christian', 'Funk', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Austin', 'Anderson', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael', 'Campoamor', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nelson', 'Jorge', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('D.J.', 'Burt', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Matt', 'Sanders', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Zack', 'Coker', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cam', 'Richins', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jimmy', 'Brennan', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Korby', 'Batesole', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kyle', 'Conger', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brallan', 'Medina', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kevin', 'Rivera', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nick', 'Valaika', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tristan', 'Gray', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Logan', 'Warmoth', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Turner', 'Buis', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Will', 'Wurth', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tyler', 'Urbach', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andrew', 'Bechtold', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Devon', 'Ortiz', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Quintin', 'Aleman', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Austin', 'Bernard', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mikey', 'Diekroeger', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Everett', 'Eynon', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Christian', 'Donahue', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Matt', 'Reardon', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luke', 'Doyle', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Brodt', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chris', 'Mathewson', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tyler', 'Brown', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Austin', 'Filiere', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Connor', 'Brady', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Bivens', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('William', 'Calderon', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Wade', 'Bailey', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chandler', 'Avant', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tim', 'Zier', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Trey', 'Harris', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Erik', 'Lunde', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jason', 'Donald', 30, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Rivera', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Eric', 'Olivo', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kyle', 'Overstreet', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Donovan', 'Solano', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Max', 'Schrock', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kolbey', 'Carpenter', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Neil', 'Walker', 29, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Leon', 'Byrd', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Danny', 'Espinosa', 27, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Reegie', 'Corona', 28, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Logan', 'Forsythe', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ross', 'Wilson', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Johnny', 'Giavotella', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Donnie', 'Walton', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Johnny', 'Caputo', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jemile', 'Weeks', 28, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Will', 'Rhymes', 31, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Connor', 'Teykl', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Guilder', 'Rodriguez', 31, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sam', 'Haggerty', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Cronenworth', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kodie', 'Tidwell', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jordan', 'Ebert', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Devin', 'Pickett', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tyler', 'Greene', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brandon', 'Lowe', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mark', 'Mathias', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ray', 'Chang', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Drew', 'Sutton', 31, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andrew', 'Geislinger', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cutter', 'Dykstra', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('D.C.', 'Arendas', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Taylor', 'Harbin', 29, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Patrick', 'Ervin', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Eric', 'Sogard', 28, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chad', 'De La Guerra', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael', 'Martinez', 32, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Josh R.', 'Johnson', 29, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Niuman', 'Romero', 30, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alonzo', 'Jones', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Darwin', 'Barney', 29, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tony', 'Thomas', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Daniel', 'Descalso', 28, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Flaherty', 28, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Charlie', 'Donovan', 17, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Shawn', 'Roof', 30, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Scott', 'Sizemore', 30, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('John', 'Tolisano', 26, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tim', 'Arakawa', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Justin', 'Henry', 29, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose G.', 'Martinez', 29, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Adams', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Devin', 'Mann', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jordan', 'Holloman', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cobie', 'Vance', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Keshawn', 'Lynch', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Eddy', 'Demurias', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brock', 'Bond', 29, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Charlie', 'Culberson', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Blake', 'Butera', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nicolas', 'Miranda', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jeremy', 'McCuin', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Omar', 'Artsen', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alejo', 'Lopez', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ethan', 'Paul', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Xavier', 'LeGrant', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Pedro', 'Okuda', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jeff', 'Kobernus', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Goins', 27, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nick', 'Franklin', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Vincent', 'Belnome', 27, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chris', 'Owings', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jason', 'Kipnis', 27, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Justin', 'Toole', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('D.J.', 'LeMahieu', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hank', 'Loforte', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robert', 'Montes', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Daino', 'Deas', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Bryce', 'Fehmel', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('George', 'Hewitt', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Angel', 'Adames', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Deacon', 'Liput', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ian', 'Nelson', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ripken', 'Reyes', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('J.D.', 'Salmon-Williams', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('C.J.', 'Ballard', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andrew', 'Noviello', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Christopher', 'Reid', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Royce', 'Lewis', 15, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Kreidler', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kramer', 'Robertson', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Fernando', 'de los Santos', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brett', 'Binning', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brandon', 'Wagner', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael', 'Strem', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Scott', 'Kingery', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jordan', 'Gore', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andrew', 'Yacyk', 19, 'Right', 'Left');
	INSERT INTO Player.SecondBasemen VALUES('Nick', 'Senzel', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Penn', 'Murfee', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ricky', 'Surum', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dee', 'Gordon', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Johnny', 'Ruiz', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Davis', 'Kirkpatrick', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nolan', 'Rogers', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sebastian', 'Diaz', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andres P.', 'Sosa', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Thomas', 'Jankins', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Taylor', 'Propst', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('David', 'Gerber', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dakota', 'Dean', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ben', 'Fisher', 20, 'Left', 'Left');
	INSERT INTO Player.SecondBasemen VALUES('Westin', 'Edrington', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jack', 'Meggs', 19, 'Left', 'Left');
	INSERT INTO Player.SecondBasemen VALUES('Cornell', 'Nixon', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Wood', 'Myers', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kameron', 'Gellinger', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nick', 'Costello', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ty', 'Kelly', 26, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Caleb', 'Kutsche', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Connor', 'Justus', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ian', 'Hamilton', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robbie', 'Thorburn', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cameron', 'Snow', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Adam', 'Walton', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andres', 'Leal', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tim', 'Borden', 15, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mason', 'Templet', 16, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tyler', 'Bowen', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dominic', 'Foscalina', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Raul', 'Juarez', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis Jose', 'Almanzar', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael', 'Massey', 16, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jaxon', 'Williams', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos', 'Cortes', 17, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rylan', 'Sandoval', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Antonio', 'Sepulveda', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ford', 'Stainback', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Quincy', 'McAfee', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cole', 'Mueller', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Najee', 'Gaskins', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Hartin', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nathan', 'Blakeney', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael', 'Griffin', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hunter', 'Grover', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Josh', 'Bonynge', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Oscar', 'Tejeda', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Justin', 'Turner', 30, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Scott', 'Savastano', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nick', 'Estrella', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gregory', 'Lamb', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Logan', 'Watkins', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Addison', 'Moss', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cord', 'Phelps', 28, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Samad', 'Taylor', 16, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jamal', 'Fraley', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Altuve', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Albert', 'Cartwright', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Skyler', 'Pichardo', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Noah', 'Williams', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Bailey', 'Mullins', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ben', 'Baird', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rafael', 'Ynoa', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cyrillo', 'Watson', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andy', 'Simunic', 29, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cal', 'Krueger', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Elmore', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Conner', 'Eddy', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Corbin', 'Bice', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jacob', 'Snider', 16, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kendell', 'Luquis', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Angel', 'Franco', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Steve', 'Lombardozzi', 26, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andy', 'Vasquez', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alex', 'Buchholz', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dean', 'Anna', 28, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cole', 'Figueroa', 27, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Elian', 'Herrera', 30, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brandon', 'Douglas', 29, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Angelys', 'Nina', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Drew', 'Garcia', 28, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Skyler', 'Stromsmoe', 30, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gerson', 'Montilla', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Travis', 'Adair', 27, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Corban', 'Joseph', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Emerson', 'Landoni', 26, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jarek', 'Cunningham', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Josh', 'Satin', 30, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brian', 'Dozier', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Toussen', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Elevys', 'Gonzalez', 25, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brock', 'Holt', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tyler', 'Bortnick', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Edwin', 'Garcia', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cesar', 'Hernandez', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Adrian', 'Sanchez', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sean', 'Nicol', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Grant', 'Green', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Scooter', 'Gennett', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Fidel', 'Pena', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael', 'Freeman', 27, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Philip', 'Gosselin', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brodie', 'Greene', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Devin', 'Lohman', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robel', 'Garcia', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Daniel', 'Arcila', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Brett', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Taylor', 'Lindsey', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chih Fang', 'Pan', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alexis', 'Aguilar', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sammie', 'Starr', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hector', 'Guevara', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Derek', 'Dietrich', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robby', 'Price', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos', 'Alonso', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Angelo', 'Gumbs', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Rosario', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('B.J.', 'Guinn', 25, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Patrick', 'Brady', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Bryan', 'Brito', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kelson', 'Brown', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Barrett', 'Kleinknecht', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sean', 'Coyle', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Corey', 'Jones', 27, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Colin', 'Walsh', 25, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sammy', 'Diaz', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ronald', 'Torreyes', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jedd', 'Gyorko', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Josh', 'Rutledge', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jonathan', 'Schoop', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kolten', 'Wong', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Garrett', 'Weber', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gerardo', 'Reyes', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis J.', 'Perez', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Breyvic', 'Valera', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dimas', 'Ponce', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tommy', 'La Stella', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ashley', 'Ponce', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ariel', 'Soriano', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael R.', 'Johnson', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Todd', 'Hankins', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Anderson', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Juan', 'Ciriaco', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Taylor', 'Featherston', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jason', 'Krizan', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Scott', 'Wingo', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Seth', 'Moranda', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cory', 'Spangenberg', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Joe', 'Panik', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Renaldo', 'Jenkins', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Adam', 'Pettersen', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dan', 'Gamache', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jace', 'Peterson', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jon', 'Berti', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Justin', 'Atkinson', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chris', 'Bostick', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Casey', 'McElroy', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yhoxian', 'Medina', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mookie', 'Betts', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Christian', 'Lopes', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Danny', 'Lockhart', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Wright', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ty', 'Washington', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos', 'Sanchez', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rougned', 'Odor', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Vance', 'Albitz', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gioskar', 'Amaya', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jorge', 'Rivero', 26, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos F.', 'Garcia', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Peraza', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alexander', 'Mercedes', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Miguel E.', 'Mendez', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Thomas', 'Di Benedetto', 29, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Leo', 'Rodriguez', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ulises', 'Montilla', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dilson', 'Herrera', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chris', 'McFarland', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kenny', 'Diekroeger', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alex', 'Yarbrough', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Joe', 'Sclafani', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chris', 'Wolfe', 25, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ross', 'Heffley', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Levi', 'Hyams', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jesmuel', 'Valentin', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Branden', 'Kaupe', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tony', 'Renda', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Fernando', 'Perez', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jacob', 'Wilson', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brett', 'Wiley', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Stephen', 'Bruno', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tim', 'Saunders', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Deiner', 'Lopez', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kody', 'Eaves', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sherman', 'Johnson', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Zach', 'Babitt', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Darnell', 'Sweeney', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Wendell', 'Rijo', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Joe', 'Wendle', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Timmy', 'Lopes', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Avery', 'Romero', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jalen', 'Goree', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('River', 'Stevens', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Anthony', 'Caronia', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Pedro', 'Toribio', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Juan', 'Santana', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Solano', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alberto', 'Robles', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan M.', 'Jones', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Claudio', 'Bautista', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Blake', 'Barber', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yeixon', 'Ruiz', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Angelo', 'Mora', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Max', 'Moroff', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tommy', 'Coyle', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Douglas', 'Duran', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Avain', 'Rachal', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Joey', 'DeMichele', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Micah', 'Johnson', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rob', 'Refsnyder', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alec', 'Mehrten', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cesar', 'Galvez', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Devon', 'Travis', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tyler', 'Hanover', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Harold', 'Castro', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Justin', 'Jirschele', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Travis', 'Demeritte', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cavan', 'Biggio', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tony', 'Kemp', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kensuke', 'Tanaka', 33, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('L.J.', 'Mazzilli', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Steve', 'Wilkerson', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Lonnie', 'Kauppila', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Josh', 'Van Meter', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Miguel', 'Dilone', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rolando', 'Segovia', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gosuke', 'Katoh', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kevin', 'Williams', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Riley', 'Unroe', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Elliott', 'Barzilli', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yariel', 'Vargas', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('James', 'Roberts', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dalton', 'Dulin', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Richy', 'Pedroza', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Willie', 'Calhoun', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryne', 'Birk', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brandon', 'Dixon', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tucker', 'Nathans', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kean', 'Wong', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Matt', 'Reida', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Takuya', 'Tsuchida', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Domingo', 'Leyba', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Dale', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jamie', 'Westbrook', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sam', 'Dove', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Austin', 'Bailey', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('James E.', 'McDonald', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael', 'Benjamin', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Raul', 'Rivas', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Elys', 'Ugueto', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Fernery', 'Ozuna', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andy', 'Peterson', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Derek', 'Odell', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Christian', 'Stringer', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Franklin', 'Correa', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Miguel', 'Patino', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jhon Meison', 'Herrera', 16, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Wilson', 'Soriano', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jean', 'Estrella', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Melvin', 'Santana', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Victor', 'Velasquez', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Bryant', 'Flete', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ordomar', 'Valdez', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mason', 'Katz', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Deiferson', 'Barreto', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Angel', 'Rojas', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Bill', 'Pujols', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robelys', 'Reyes', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Eliezer', 'Alvarez', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Willi', 'Castro', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rafael', 'Gomez', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ravel', 'Hernandez', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose Luis', 'Javier', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Logan', 'Davis', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jack', 'Mayfield', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jeff', 'McNeil', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hector L.', 'Martinez', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jesus Fernando', 'Lopez', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nathan', 'Orf', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos', 'Ozuna', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robinson', 'Torres', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Bryan', 'Mejia', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Leon', 'Canelon', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jean', 'Rodriguez', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jonathan', 'Matute', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Rengifo', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Frankeny', 'Fernandez', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Iramis', 'Olivencia', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brennan', 'Middleton', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Erich', 'Weiss', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Reed', 'Gragnani', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Reynoso', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos', 'Asuaje', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Adam', 'Law', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tyler', 'Shryock', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Coty', 'Blanchard', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Lindemuth', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kevin', 'Kuntz', 24, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jimmy', 'Allen', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Derek', 'Campbell', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Taylor', 'Terrasas', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Federico', 'Castagnini', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tanner', 'Vavra', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Taylor L.', 'Johnson', 24, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Trevor', 'Sprowl', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Henry', 'Castillo', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Will', 'Callaway', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ro', 'Coleman', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yeudi', 'Grullon', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alejandro', 'Diaz', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('David', 'Harris', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Joe', 'Bennie', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Santo', 'Marte', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rafael', 'Oliveras', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mike', 'Giuffre', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Garrett', 'Smith', 25, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kyle', 'Attl', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('David H.', 'Garcia', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ismael', 'Dionicio', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Monasterio', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Sergio', 'Lamas', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Audry', 'Santana', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Oviel', 'Florentino', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Zambrano', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Valenzuela', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Bryan', 'Cuevas', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Reynaldo', 'Bruguera', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('William', 'Ireton', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Pedro', 'Flores', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gonzalo', 'Galastica', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Benoit', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rafael', 'Barrios', 18, 'Left', 'Left');
	INSERT INTO Player.SecondBasemen VALUES('Dalfis', 'Ortiz', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Humberto', 'Garcia', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jesus A.', 'Gonzalez', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yoan', 'Andujar', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Erlin', 'Cerda', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose G.', 'Rodriguez', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gregoris', 'Hidalgo', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Arturo', 'Michelena', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Offerman', 'Collado', 18, 'Right', 'Left');
	INSERT INTO Player.SecondBasemen VALUES('Juan', 'Moreno', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rony', 'Cabrera', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Edgar', 'Solano', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rafael', 'Toribio', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brooks', 'Conrad', 35, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tsubasa', 'Nakatani', 30, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Masashi', 'Nohara', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryosuke', 'Shibata', 27, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tetsuya', 'Sakaguchi', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kosei', 'Fujii', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Shinya', 'Arasaki', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Takeshi', 'Aono', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hisao', 'Heiuchi', 33, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yu-Cheng', 'Chang', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos', 'Sepulveda', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Juan Carlos', 'Torriente', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alex', 'Guerrero', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose Miguel', 'Fernandez', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Enrique', 'Bicet', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hector', 'Olivera', 29, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yeison', 'Pacheco', 30, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dayan', 'Garcia', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Danel', 'Castro', 38, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Anibal', 'Medina', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yandrys', 'Canto', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yaxsiel', 'Quiros', 28, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andy', 'Sarduy', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alay', 'Lago', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andy', 'Garcia', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yasmani', 'Viera', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Reinier', 'Llanes', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Lester J.', 'Lopez', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Maikel', 'Caceres', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ruben', 'Valdes Exposito', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michel', 'Rodriguez', 37, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Juan Miguel', 'Vazquez', 29, 'Left', 'Left');
	INSERT INTO Player.SecondBasemen VALUES('Alejandro', 'Ortiz', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Joel', 'Avalo', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dariel', 'Oliva', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yordan', 'Batista', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yosvani', 'Garcia', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rafael', 'Hidalgo', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Alfonso', 34, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yoilan', 'Cerse', 27, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yoan', 'Moncada', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jhoyce', 'Su Casella', 32, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Pavel', 'Quesada', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yunier', 'Corvo', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis Angel', 'Sanchez', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Lazaro', 'Godinez', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Raciel', 'Seijo', 28, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ramon A.', 'Castro', 35, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Zair', 'Koeiman', 25, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Junior', 'Vasquez', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Urias', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Roosevert', 'Chal', 20, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jorge', 'Quiterio', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jorge', 'Andrade', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Pedro', 'Estaba', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ariel', 'Montesino', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gabriel', 'Ynfante', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rigoberto', 'Terrazas', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alvin', 'Maracaro', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Reed', 'Harper', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Tirson', 'Guzman', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Allison', 'Reyes', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Juan', 'Lorenzo', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Junior', 'Valera', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Javier', 'Godard', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jean Carlo', 'Rodriguez', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Thomas', 'Alvarez', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Edwin', 'Lora', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Darinel', 'Rodriguez', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jilbert', 'Rosario', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alexander', 'Perdomo', 21, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Olvy', 'Marte', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hector', 'Valdez', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Gustavo', 'Barrios', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Manuel', 'Vizcaino', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Robert', 'Antunez', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Marco', 'Guzman', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Cesar', 'Baez', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Rodrigo', 'Ayarza', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Albert', 'Herrera', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Drew', 'Rossi', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yolberth', 'Gideon', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose An.', 'Reyes', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Franklin', 'Vargas', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Vidauri', 'Saba', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos E.', 'Rivero', 17, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hazzent', 'Torrealba', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Efrin', 'Ortega', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Keyder', 'Aristigueta', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Goldny', 'Mills', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yefry', 'Reyes', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Leisman', 'Acosta', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Julio', 'Mendez', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Arraez', 17, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis M.', 'Flores', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Wadye', 'Ynfante', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ricardo', 'Perez', 19, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Anthony', 'Cantillo', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis A.', 'Silva', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Barbaro', 'Urquiola', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Anibal', 'Sierra', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dainier', 'Rodriguez', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Willian', 'Gonzalez', 24, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jordan', 'Edgerton', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Matt', 'Heck', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Stephen', 'Ventimilia', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jonathan', 'Oquendo', 19, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Chase', 'Aldridge', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose J.', 'Lozada', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Franklin', 'Tineo', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Diego', 'Francisco', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Alexander', 'Hernandez', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Louis-Philippe', 'Pelletier', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('J.J.', 'Franco', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Seth', 'Spivey', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Steven', 'Patterson', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Darren', 'Seferina', 21, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Javier', 'Agelvis', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Galli', 'Cribbs', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Beaufond', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis', 'Joseph', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Henrry', 'Pedra', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dayne', 'Parker', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Anardo', 'Peralta', 18, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Dillon', 'Everett', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Michael', 'Massi', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Oscar', 'Sanay', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jose', 'Marquez', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Esequiel', 'Delgado', 17, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Juan', 'Pineda', 17, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ryan', 'Metzler', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ty', 'McFarland', 23, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mike', 'Abreu', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andrew', 'Daniel', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jeremy', 'Rivera', 20, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Hector', 'Lorenzana', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andrew', 'Ely', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('William', 'Fulmer', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Billy', 'Fleming', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jake', 'Gronsky', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Walker', 'Whitworth', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brett', 'Pirtle', 23, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Blade', 'Richard', 15, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Brice', 'Turang', 15, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Takuma', 'Hasegawa', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Blaine', 'Prescott', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Antonio', 'Nunez', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Mason', 'Davis', 22, 'Both', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jonathan', 'Johnson', 26, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ho-young', 'Son', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Nathan', 'Sopena', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Amos', 'Ramon', 31, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ren', 'Yasui', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kento', 'Itohara', 22, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Orlando', 'Santos', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Frank', 'Peralta', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Orileidis', 'Pons', 22, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Emilio', 'Bonza', 26, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luis Michel', 'Rodriguez', 18, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Carlos Ernesto', 'Moreno', 25, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Kevin', 'Gonzalez Rodriguez', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Santiago', 'Torres', 20, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yandry', 'Reyes', 25, 'Left', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Denis', 'Pena', 19, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Yosmani', 'Garcia', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Jorge', 'Contreras', 23, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Andy', 'Pacheco', 21, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ciro', 'Barrios', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Ezequiel', 'Rodriguez', 18, 'Right', 'Right');
	INSERT INTO Player.SecondBasemen VALUES('Luke', 'Maddox', 18, 'Left', 'Right');
END
GO
